name: 'Upload BOM to Dependency-Track'
author: Patrick Dwyer
description: 'Uploads a CycloneDX software bill of materials to a Dependency-Track server'
inputs:
  serverhostname:
    description: 'Dependency-Track hostname'
    required: true
  port:
    description: 'Dependency-Track port'
    required: false
    default: '443'
  protocol:
    description: 'Dependency-Track protocol'
    required: false
    default: 'https'
  apikey:
    description: 'Dependency-Track API key'
    required: true
  project:
    description: 'Project in Dependency-Track'
    required: false
  projectname:
    description: 'Project name in Dependency-Track'
    required: false
  projectversion:
    description: 'Project version in Dependency-Track'
    required: false
  autocreate:
    description: "Automatically create the project in Dependency-Track if it doesn't exist"
    default: 'false'
    required: false
  bomfilename:
    description: 'Path and filename of the BOM'
    default: 'bom.xml'
    required: false
  parent:
    description: 'Parent project in Dependency-Track'
    required: false
  parentname:
    description: 'Parent name in Dependency-Track'
    required: false
  parentversion:
    description: 'Parent version in Dependency-Track'
    required: false
outputs:
  token:
    description: 'The token response from Dependency-Track after SBOM file upload'
runs:
  using: 'node20'
  main: 'index.js'
