name: 'Upload BOM to Dependency-Track'
author: Patrick Dwyer
description: 'Uploads a CycloneDX software bill of materials to a Dependency-Track server'
inputs:
  serverHostname:
    description: 'Dependency-Track hostname'
    required: true
  port:
    description: 'Dependency-Track port'
    required: false
    default: '443'
  protocol:
    description: 'Dependency-Track protocol'
    required: false
    default: 'https'
  apiKey:
    description: 'Dependency-Track API Key'
    required: true
  project:
    description: 'Project in Dependency-Track'
    required: false
  projectName:
    description: 'Project name in Dependency-Track'
    required: false
  projectVersion:
    description: 'Project version in Dependency-Track'
    required: false
  autoCreate:
    description: "Automatically create the project in Dependency-Track if it doesn't exist"
    default: 'false'
    required: false
  bomFilename:
    description: 'Path and filename of the BOM'
    default: 'bom.xml'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
